PLAYER = '@'
ZOMBIE = 'Z'
VAMPIRE = 'V'
GHOST = 'G'
OGRE = 'O'
SNAKE = 'S'


# gamestate
GAMEOVER = 0
NORMAL = 1
# also gamestate
TREASURE = '*'
FOOD = '%'
POTION = '!'
SCROLL = '?'
WEAPON = ')'


HEALTH = 'h'
MAX_HEALTH = 'H'
DEXTERITY = 'd'
STRENGTH =  'n'
CURRENT_WEAPON = 'w'

ITEMS = (FOOD, POTION, SCROLL, WEAPON) 

FULL_BACKPACK = (FOOD, POTION, SCROLL, WEAPON, CURRENT_WEAPON, DEXTERITY, STRENGTH, HEALTH, MAX_HEALTH, TREASURE)
BACKPACK_SHOW_MENU = {'j': FOOD, 'h': WEAPON, 'e': SCROLL, 'k':POTION}