
# ┏  # U+250F BOX DRAWINGS HEAVY DOWN AND RIGHT
# ┓  # U+2513 BOX DRAWINGS HEAVY DOWN AND LEFT
# ┗  # U+2517 BOX DRAWINGS HEAVY UP AND RIGHT  
# ┛  # U+251B BOX DRAWINGS HEAVY UP AND LEFT
# ┃  # U+2503 BOX DRAWINGS HEAVY VERTICAL
# ━  # U+2501 BOX DRAWINGS HEAVY HORIZONTAL
# ┣  # U+2523 BOX DRAWINGS HEAVY VERTICAL AND RIGHT
# ┫  # U+252B BOX DRAWINGS HEAVY VERTICAL AND LEFT
# ┳  # U+2533 BOX DRAWINGS HEAVY DOWN AND HORIZONTAL
# ┻  # U+253B BOX DRAWINGS HEAVY UP AND HORIZONTAL
# ╋  # U+254B BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
PLAYER = '@'
ROOMS = 9
OFFSET = 2
MIN_ROOM_WIDTH = 8 + OFFSET
MAX_ROOM_WIDTH = 20 + OFFSET
MIN_ROOM_HEIGHT = 6 + OFFSET
MAX_ROOM_HEIGHT = 15 + OFFSET

MIN_ROOM_AREA = MIN_ROOM_WIDTH * MIN_ROOM_HEIGHT
MAX_ROOM_AREA = MAX_ROOM_WIDTH * MAX_ROOM_HEIGHT
CORRIDOR = 1
CORR_VER = '┃' #'║' # '·'
CORR_HOR = '━' #'═' # '·'

WALL_HOR = '─' # '─'
WALL_VER = '│' # '│'
# CORNER = '-'
ULCR = '┌' # '┌'
BLCR = '└' # '└'
URCR = '┐' # '┐' ┓
BRCR = '┘' # '┘'
ROOM_CORNERS = (ULCR, URCR, BRCR, BLCR)
ROOM_WALLS = (ULCR, URCR, BRCR, BLCR, WALL_HOR, WALL_VER)
ULC = '┏' #'╔'  '┌'
BLC = '┗' #'╚'  '└'
URC = '┓'  #'╗' # '┐'
BRC = '┛' # '╝' # '┘'
FLOOR = '·'
GROUND = ' '
DOOR_H = '┃' # '╫' # '╬' '┼' door on horizontal wall
DOOR_V =  '━' #'╪' # '╬' '┼' door on vertical wall
WIDTH = 100
HEIGHT = 50