SHIFT = 1
INFO_MENU_WIDTH = 25
INFO_MENU_HEIGHT = 14
INFO_MENU_POS_Y = 0
INFO_MENU_POS_X = 100

REC_MENU_POS_Y = INFO_MENU_POS_Y
REC_MENU_POS_X = INFO_MENU_POS_X + INFO_MENU_WIDTH
REC_MENU_WIDTH = INFO_MENU_WIDTH
REC_MENU_HEIGHT = INFO_MENU_HEIGHT

BACKPACK_MENU_HEIGHT = 12