
# ┏  # U+250F BOX DRAWINGS HEAVY DOWN AND RIGHT
# ┓  # U+2513 BOX DRAWINGS HEAVY DOWN AND LEFT
# ┗  # U+2517 BOX DRAWINGS HEAVY UP AND RIGHT  
# ┛  # U+251B BOX DRAWINGS HEAVY UP AND LEFT
# ┃  # U+2503 BOX DRAWINGS HEAVY VERTICAL
# ━  # U+2501 BOX DRAWINGS HEAVY HORIZONTAL
# ┣  # U+2523 BOX DRAWINGS HEAVY VERTICAL AND RIGHT
# ┫  # U+252B BOX DRAWINGS HEAVY VERTICAL AND LEFT
# ┳  # U+2533 BOX DRAWINGS HEAVY DOWN AND HORIZONTAL
# ┻  # U+253B BOX DRAWINGS HEAVY UP AND HORIZONTAL
# ╋  # U+254B BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL

EXIT =  '█' #'>'

CORRIDOR = 9
CORR_VER = '┃' #'║' # '·'
CORR_HOR = '━' #'═' # '·'

WALL_HOR = '─' # '─'
WALL_VER = '│' # '│'
# CORNER = '-'
TLCR = '┌' # '┌'
BLCR = '└' # '└'
TRCR = '┐' # '┐' ┓
BRCR = '┘' # '┘'
ROOM_CORNERS = (TLCR, TRCR, BRCR, BLCR)
ROOM_WALLS = (TLCR, TRCR, BRCR, BLCR, WALL_HOR, WALL_VER)
TLC = '┏' #'╔'  '┌'
BLC = '┗' #'╚'  '└'
TRC = '┓'  #'╗' # '┐'
BRC = '┛' # '╝' # '┘'
FLOOR = '\033[2m·\033[0m' #'·'
GROUND = ' '
DOOR_H = '┃' # '╫' # '╬' '┼' door on horizontal wall
DOOR_V =  '━' #'╪' # '╬' '┼' door on vertical wall






